In [ ]:
import numpy as np

## Appliquer une opération à chaque élément d'un tableau numpy

In [39]:
a = np.arange(1000)

In [40]:
%timeit [x**2 + 2*x -1 for x in a]

365 μs ± 2.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [41]:
%timeit a**2 + 2*a -1

4.97 μs ± 92.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [48]:
a = np.arange(1, 1_000_000, dtype=np.float64)

In [49]:
%timeit -r 1 -n 1 np.sqrt(a)

8.26 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [50]:
%timeit -r 1 -n 1 np.sqrt(a, out=a)

1.65 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [51]:
a[:5]

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

## Appliquer une opération à un élément d'un tableau numpy avec `at`

In [52]:
np.log.at(a, [2, 4])

In [53]:
a[:5]

array([1.        , 1.41421356, 0.54930614, 2.        , 0.80471896])

In [57]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
np.sum(a)

np.int64(45)

In [59]:
np.sum(a)

np.int64(45)

In [60]:
np.sum(a, axis=0)

array([12, 15, 18])

In [61]:
np.sum(a, axis=1)

array([ 6, 15, 24])

In [62]:
a = np.arange(1, 10, dtype=np.float64).reshape(3, 3)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [63]:
a[1, 1] = np.nan

In [64]:
a

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [65]:
np.mean(a)

np.float64(nan)

In [66]:
np.nanmean(a)

np.float64(5.0)

In [67]:
np.nanmax(a)

np.float64(9.0)