In [17]:
import numpy as np

## Appliquer une opération à chaque élément d'un tableau numpy

Effectuer des calculs sur des tableaux numpy prennent moins de temps que sur des objets python natif comme les listes

In [18]:
a = np.arange(1000)

In [19]:
%timeit [x**2 + 2*x -1 for x in a]

262 μs ± 20.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [20]:
%timeit a**2 + 2*a -1

5.24 μs ± 624 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [21]:
a = np.arange(1, 1_000_000, dtype=np.float64)

In [22]:
%timeit -r 1 -n 1 np.sqrt(a)

5.05 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [23]:
%timeit -r 1 -n 1 np.sqrt(a, out=a)

1.6 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [24]:
a[:5]

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [25]:
a

array([  1.        ,   1.41421356,   1.73205081, ..., 999.9985    ,
       999.999     , 999.9995    ], shape=(999999,))

## Appliquer une opération à certains éléments d'un tableau numpy avec `at`

Ceci a pour conséquence une modification en place

In [26]:
np.log.at(a, [2, 4])

In [27]:
a

array([1.00000000e+00, 1.41421356e+00, 5.49306144e-01, ...,
       9.99998500e+02, 9.99999000e+02, 9.99999500e+02], shape=(999999,))

In [28]:
a[:5]

array([1.        , 1.41421356, 0.54930614, 2.        , 0.80471896])

In [29]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## `np.sum()`

In [40]:
np.sum(a)

np.float64(nan)

In [41]:
np.sum(a)

np.float64(nan)

In [42]:
np.sum(a, axis=0)

array([12., nan, 18.])

In [43]:
np.sum(a, axis=1)

array([ 6., nan, 24.])

## `np.mean()`

In [44]:
a = np.arange(1, 10, dtype=np.float64).reshape(3, 3)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [45]:
a[1, 1] = np.nan

In [46]:
a

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

Toutes opérations éffectués sur des NaN produisent en sortie un NaN

In [37]:
np.mean(a)

np.float64(nan)

## Les fonctions préfixées de `nan` ignorent les objets NaN

### `np.nanmean`

In [38]:
np.nanmean(a)

np.float64(5.0)

### `np.nanmax`

In [39]:
np.nanmax(a)

np.float64(9.0)