In [124]:
import numpy as np

Numpy est librairie qui permet de manipuler des tableaux multidimensionnels

In [125]:
np.ones(shape=3)

array([1., 1., 1.])

In [126]:
np.zeros(shape=3)

array([0., 0., 0.])

In [127]:
np.ones(shape=(2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [128]:
np.zeros(shape=(2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [129]:
np.ones(shape=(2, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [130]:
np.zeros(shape=(2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

Voici un tableau à deux dimensions avec 2 lignes et 2 colonnes

In [131]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [132]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

Les tableaux numpy sont des objets mutables, qui occupent une zone contigüe de mémoire et ne peuvent pas être étendu

In [133]:
a[1, 1] = 18

In [134]:
a

array([[ 1.,  1.],
       [ 1., 18.]])

In [135]:
a[0][1] = 20

In [136]:
a

array([[ 1., 20.],
       [ 1., 18.]])

Numpy fournit des dtype(type de données scalaire)

In [137]:
np.sctypeDict

{'bool': numpy.bool,
 'float16': numpy.float16,
 'float32': numpy.float32,
 'float64': numpy.float64,
 'longdouble': numpy.longdouble,
 'complex64': numpy.complex64,
 'complex128': numpy.complex128,
 'clongdouble': numpy.clongdouble,
 'bytes_': numpy.bytes_,
 'str_': numpy.str_,
 'void': numpy.void,
 'object_': numpy.object_,
 'datetime64': numpy.datetime64,
 'timedelta64': numpy.timedelta64,
 'int8': numpy.int8,
 'byte': numpy.int8,
 'uint8': numpy.uint8,
 'ubyte': numpy.uint8,
 'int16': numpy.int16,
 'short': numpy.int16,
 'uint16': numpy.uint16,
 'ushort': numpy.uint16,
 'int32': numpy.int32,
 'intc': numpy.int32,
 'uint32': numpy.uint32,
 'uintc': numpy.uint32,
 'int64': numpy.int64,
 'long': numpy.int64,
 'uint64': numpy.uint64,
 'ulong': numpy.uint64,
 'longlong': numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'intp': numpy.int64,
 'uintp': numpy.uint64,
 'double': numpy.float64,
 'cdouble': numpy.complex128,
 'single': numpy.float32,
 'csingle': numpy.complex64,
 'half': numpy.

Convertir une liste python en un tableau numpy(de type ndarray en spécifiant le dtype)

In [138]:
a = np.array([1, 100, 110], dtype=np.int8)

Obtenir au dtype d'un tableau

In [139]:
a.dtype

dtype('int8')

Obtenir la taille d'éléments du tableau en octet

In [140]:
a.itemsize

1

Obtenir la taille du tableau en octet

In [141]:
a.nbytes

3

In [142]:
np.array([1, 4.5, 127], dtype=np.int8)

array([  1,   4, 127], dtype=int8)

Conversion implicite avec des valeurs invalides sans définition de dtype
> Le type objet NaN (Not a Number) ne sont compatible qu'avec le type float

In [143]:
a = np.array([1, 2, np.nan])

In [144]:
a.dtype

dtype('float64')

In [145]:
a

array([ 1.,  2., nan])

Conversion silencieuse des valeurs invalides avec la définition de dtype
> Ceci lèvera une exception avec un dtype différent de float à cause du type objet NaN (Not a Number)

In [ ]:
a = np.array([1, 2, np.nan], dtype=np.int32)

In [ ]:
np.sctypeDict['str']

In [ ]:
a = np.array(['spam', 'bean'], dtype=np.str_)

In [ ]:
a

In [ ]:
a = np.array(['spam', 'beans'], dtype=np.str_)

In [ ]:
a

In [ ]:
a = np.array(['spam', 'beans'], dtype=(np.str_, 2))

In [ ]:
a

`object` permet de spécifier un dtype qui sert à stocker les références vers les objets et non les objets eux même dans le tableau numpy

In [ ]:
a = np.array([[1, 2], [3, 4]], dtype=np.object_)

In [ ]:
a

## La différence d'encodage de type entre numpy et python natif

In [ ]:
np_1_int_8_bit = np.int8(1)
print(np_1_int_8_bit)

In [ ]:
np_1_int_8_bit.dtype

In [ ]:
py_natif = 1
type(py_natif)

In [ ]:
np_1_int_8_bit == py_natif

In [ ]:
np_1_int_8_bit is py_natif

## `np.array`

In [ ]:
numpy_array = np.array([12, 25, 32, 55])
numpy_array

## `np.arange`

In [ ]:
numpy_range = np.arange(10)
numpy_range

In [ ]:
numpy_array_f = np.arange(1.0, 2.0, 0.1)
numpy_array_f

## `np.linspace`

In [ ]:
X = np.linspace(0., 10., 50)
X

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.ion()

In [ ]:
Y = np.cos(X)
plt.plot(X, Y)

## Programmation vectorielle

In [ ]:
Z = np.cos(X)**2 + np.sin(X)**2 + 3
plt.plot(X, Z)

### Universal function ou ufunc

Ces fonctions implémentent un mécanisme qui permet à la fonction de s'exécuter sur chaque terme d'un tableau par exemple.

#### Passer d'une fonction scalaire à une ufunc avec le décorateur `@np.vectorize`

In [ ]:
@np.vectorize
def scalar_function(x):
    return x**2 + 2*x + (1 if x <= 0 else 10)

In [ ]:
X = np.linspace(-5, 5, 1000)
Y = scalar_function(X)
plt.plot(X, Y)

## Le type d'un tableau numpy

In [ ]:
a = np.array([1, 2, 4, 8])
a.dtype

In [ ]:
a = np.array([1, 2, 4, 8.])
a.dtype

In [ ]:
a

In [ ]:
a = np.array([1, 2, 4, 8j])
a.dtype

In [ ]:
a

In [ ]:
c2 = np.array([1, 2, 4, 8j], dtype=np.complex64)
a.dtype

In [ ]:
a, a.dtype

In [ ]:
a = np.array([1, 2, 4, 8])
a.dtype

In [ ]:
a[0] = 3.14
a

## La différence de taille mémoire entre un tableau dynamique python(list) et un tableau numpy

In [ ]:
from sys import getsizeof
array_py = [0 for _ in range(10**6)]
size = getsizeof(array_py)
print(f"La taille de la liste python <array_py> qui stocke 1_000_000 de data est de {size} octets")

In [ ]:
array_np = np.zeros(10**6, dtype=np.int8)
size = getsizeof(array_np)
print(f"La taille d'un tableau numpy <array_np> qui stocke 1_000_000 de data est de {size} octets, soit 8 fois moins qu'une liste python")