# Calcul d'algèbre linéaire

In [118]:
import numpy as np


## Manipulation des matrices et vecteurs

### Produit Matriciel avec `np.dot()`, `dot()` ou `@` (opérateur *ad hoc* pour numpy)

In [119]:
m1 = np.array([[1, 1],
               [2, 2]])
print(m1)

[[1 1]
 [2 2]]


In [120]:
m2 = np.array([[10, 10],
               [30, 40]])
print(m2)

[[10 10]
 [30 40]]


In [121]:
np.dot(m1, m2)

array([[ 40,  50],
       [ 80, 100]])

In [122]:
m1.dot(m2)

array([[ 40,  50],
       [ 80, 100]])

In [123]:
m1 @ m2

array([[ 40,  50],
       [ 80, 100]])

In [124]:
m2 @ m1

array([[ 30,  30],
       [110, 110]])

### Produit scalaire avec `np.dot()`, `dot()` ou `@`

In [125]:
v1 = np.array([1, 2, 3])
print(v1)

[1 2 3]


In [126]:
v2 = np.array([4, 5, 6])
print(v2)

[4 5 6]


In [127]:
scalar_product = np.dot(v1, v2)

In [128]:
scalar_product = v1.dot(v2)
print(scalar_product)

32


In [129]:
scalar_product = v1 @ v2
print(scalar_product)

32


### Transposée de matrice avec `T` ou `transpose()`

In [130]:
m = np.arange(4).reshape(2, 2)
print(m)

[[0 1]
 [2 3]]


In [131]:
print(m.T)

[[0 2]
 [1 3]]


In [132]:
print(m.transpose())

[[0 2]
 [1 3]]


### Matrice d'identité avec `np.eye()` ou `np.identity()`

In [133]:
np.eye(4, dtype=np.int8)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [134]:
np.identity(4, dtype=np.int8)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

### Matrice diagonales avec `np.diag()`

In [135]:
M = np.arange(4) + 10 * np.arange(4)[:, np.newaxis]
print(M)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


In [136]:
# Extraire la diagonale principale
D = np.diag(M)
print(D)

[ 0 11 22 33]


In [137]:
# Construire une matrice à partir d'une diagonale
M2 = np.diag(D)
print(M2)

[[ 0  0  0  0]
 [ 0 11  0  0]
 [ 0  0 22  0]
 [ 0  0  0 33]]


### Déterminant de matrice avec `np.linalg.det()`

In [138]:
M = np.array([[0, -1],
              [1, 0]])
print(M)

[[ 0 -1]
 [ 1  0]]


In [139]:
np.linalg.det(M) == 1

np.True_

### Valeur et vecteur propre de matrice avec `np.linalg.eig`

- Un vecteur propre est une flèche (un vecteur) dont la direction ne change pas lorsqu'on lui applique une transformation géométrique ou une matrice.

 - La valeur propre est le nombre qui indique de combien ce vecteur est étiré, réduit ou inversé lors de cette transformation.

 Imaginez une transformation (comme un zoom ou une déformation) dans l'espace.
 - La plupart des vecteurs changent à la fois de taille et de direction.

  - Les vecteurs propres ont un comportement spécial : ils gardent exactement la même direction, ils sont juste multipliés par un facteur d'échelle.

  - Ce facteur d'échelle est la valeur propre (souvent notée `lambda`).

Obtenir des valeurs et vecteurs propres

In [140]:
S = np.array([[0, 1],
              [1, 0]])

In [141]:
values, vectors = np.linalg.eig(S)

In [142]:
values

array([ 1.+0.j, -1.+0.j])

In [143]:
vectors

array([[ 0.70710678+0.j, -0.70710678+0.j],
       [ 0.70710678+0.j,  0.70710678+0.j]])

### Systèmes d'équations avec `np.linalg.solve`

In [144]:
x, y, z = 1, 2, 3

In [145]:
3*x + 2*y + z

10

In [146]:
2*x + 3*y + 4*z

20

In [147]:
5*x + 2*y + 5*z

24

In [148]:
coefficients= np.array([
    [3, 2, 1],
    [2, 3, 4],
    [5, 2, 6],
])

In [149]:
constants = [
    10,
    20,
    27,
]

In [150]:
X, Y, Z = np.linalg.solve(coefficients, constants)

In [151]:
print(X)

0.9999999999999994


In [152]:
print(Y)

1.9999999999999996


In [153]:
print(Z)

3.0000000000000004
