In [1]:
import numpy as np

In [2]:
a = np.array((1, 2, 3))

In [3]:
b = np.array((4, 5, 6))

In [4]:
a * b

array([ 4, 10, 18])

In [5]:
c = np.array([5])

In [6]:
a * c

array([ 5, 10, 15])

In [7]:
a * 5

array([ 5, 10, 15])

## Broadcasting

### Exemple 1

In [9]:
a = np.array([1, 2, 3]).reshape(1, 3)
a

array([[1, 2, 3]])

In [11]:
b = np.ones((3, 3), dtype=np.int8)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [12]:
a * b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Exemple 2

In [13]:
a = np.array([1, 2, 3]).reshape(3, 1)
a

array([[1],
       [2],
       [3]])

In [14]:
b = np.ones((3, 3), dtype=np.int8)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [15]:
a * b

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### Exemple 3

In [16]:
a = np.array([1, 2, 3]).reshape(3, 1)
a

array([[1],
       [2],
       [3]])

In [17]:
b = np.array([4, 5]).reshape(1, 2)
b

array([[4, 5]])

In [18]:
a * b

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])